-- Consolidated initial schema for Blixa (ColDP editor).
--
-- Squashed on 2026-07-21 from the original incremental migrations V1..V34: the deploy
-- database was wiped, so the migration history was collapsed into this single baseline.
-- Generated by pg_dump --schema-only of the fully-migrated schema (pg_dump preamble,
-- psql meta-commands, and ownership COMMENTs stripped so Flyway/JDBC runs it cleanly).


CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;

CREATE TABLE public.app_user (
    id bigint NOT NULL,
    orcid text,
    username text NOT NULL,
    email text,
    display_name text,
    given text,
    family text,
    password_hash text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    admin boolean DEFAULT false NOT NULL,
    state text DEFAULT 'ACTIVE'::text NOT NULL
);

ALTER TABLE public.app_user ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.app_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.author (
    id integer NOT NULL,
    project_id integer NOT NULL,
    alternative_id text[],
    given text,
    family text,
    suffix text,
    abbreviation_botany text,
    affiliation text,
    birth text,
    death text,
    birth_place text,
    country text,
    link text,
    remarks text,
    modified timestamp with time zone DEFAULT now() NOT NULL,
    modified_by bigint,
    version integer DEFAULT 0 NOT NULL
);

CREATE TABLE public.change (
    id integer NOT NULL,
    project_id integer NOT NULL,
    user_id integer,
    at timestamp with time zone DEFAULT now() NOT NULL,
    entity_type text NOT NULL,
    entity_id integer NOT NULL,
    operation text NOT NULL,
    diff jsonb,
    task_id integer
);

ALTER TABLE public.change ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.change_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.col_match_run (
    id bigint NOT NULL,
    project_id bigint NOT NULL,
    status text NOT NULL,
    total integer DEFAULT 0 NOT NULL,
    processed integer DEFAULT 0 NOT NULL,
    verified integer DEFAULT 0 NOT NULL,
    added integer DEFAULT 0 NOT NULL,
    updated integer DEFAULT 0 NOT NULL,
    unmatched integer DEFAULT 0 NOT NULL,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    finished_at timestamp with time zone,
    error text
);

ALTER TABLE public.col_match_run ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.col_match_run_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.discussion (
    project_id integer NOT NULL,
    id integer NOT NULL,
    title text NOT NULL,
    body text,
    status text DEFAULT 'OPEN'::text NOT NULL,
    visibility text DEFAULT 'INTERNAL'::text NOT NULL,
    author_id integer,
    author_orcid text,
    created_via text DEFAULT 'UI'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    version integer DEFAULT 0 NOT NULL
);

CREATE TABLE public.discussion_api_token (
    project_id integer NOT NULL,
    token text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.discussion_change (
    project_id integer NOT NULL,
    discussion_id integer NOT NULL,
    change_id integer NOT NULL
);

CREATE TABLE public.discussion_comment (
    project_id integer NOT NULL,
    id integer NOT NULL,
    discussion_id integer NOT NULL,
    body text NOT NULL,
    author_id integer,
    author_orcid text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    version integer DEFAULT 0 NOT NULL
);

CREATE TABLE public.discussion_follow (
    project_id integer NOT NULL,
    discussion_id integer NOT NULL,
    user_id integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.discussion_usage (
    project_id integer NOT NULL,
    discussion_id integer NOT NULL,
    usage_id integer NOT NULL
);

CREATE TABLE public.distribution (
    project_id integer NOT NULL,
    id integer NOT NULL,
    usage_id integer NOT NULL,
    area text,
    area_id text,
    gazetteer text,
    establishment_means text,
    threat_status text,
    reference_id integer,
    remarks text,
    modified timestamp with time zone DEFAULT now() NOT NULL,
    modified_by integer,
    version integer DEFAULT 0 NOT NULL
);

CREATE TABLE public.estimate (
    project_id integer NOT NULL,
    id integer NOT NULL,
    usage_id integer NOT NULL,
    estimate integer,
    type text,
    reference_id integer,
    remarks text,
    modified timestamp with time zone DEFAULT now() NOT NULL,
    modified_by integer,
    version integer DEFAULT 0 NOT NULL
);

CREATE TABLE public.export_run (
    id bigint NOT NULL,
    project_id bigint NOT NULL,
    status text NOT NULL,
    file_path text,
    file_name text,
    file_size bigint,
    name_usage_count integer DEFAULT 0 NOT NULL,
    reference_count integer DEFAULT 0 NOT NULL,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    finished_at timestamp with time zone,
    error text
);

ALTER TABLE public.export_run ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.export_run_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.id_seq (
    project_id integer NOT NULL,
    entity text NOT NULL,
    next_id integer NOT NULL
);

CREATE TABLE public.import_run (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    project_id bigint,
    status text NOT NULL,
    source_name text,
    preserve_ids boolean DEFAULT false NOT NULL,
    id_scope text,
    name_usage_count integer DEFAULT 0 NOT NULL,
    reference_count integer DEFAULT 0 NOT NULL,
    author_count integer DEFAULT 0 NOT NULL,
    issues jsonb,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    finished_at timestamp with time zone,
    error text
);

ALTER TABLE public.import_run ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.import_run_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.issue (
    id integer NOT NULL,
    project_id integer NOT NULL,
    entity_type text NOT NULL,
    entity_id integer NOT NULL,
    rule text NOT NULL,
    severity text NOT NULL,
    message text NOT NULL,
    context jsonb,
    status text DEFAULT 'OPEN'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    reviewer_id integer,
    reviewed_at timestamp with time zone
);

ALTER TABLE public.issue ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.issue_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.join_request (
    id integer NOT NULL,
    project_id integer NOT NULL,
    orcid text NOT NULL,
    name text,
    message text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.join_request ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.join_request_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.lock (
    id integer NOT NULL,
    project_id integer NOT NULL,
    entity_type text NOT NULL,
    entity_id integer NOT NULL,
    user_id integer NOT NULL,
    acquired_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    task_id integer
);

ALTER TABLE public.lock ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.lock_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.media (
    project_id integer NOT NULL,
    id integer NOT NULL,
    usage_id integer NOT NULL,
    url text,
    type text,
    title text,
    creator text,
    license text,
    link text,
    remarks text,
    modified timestamp with time zone DEFAULT now() NOT NULL,
    modified_by integer,
    version integer DEFAULT 0 NOT NULL
);

CREATE TABLE public.merge_run (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    source_project_id bigint NOT NULL,
    target_project_id bigint NOT NULL,
    status text NOT NULL,
    mode text,
    transactional boolean,
    plan jsonb,
    metrics jsonb,
    issues jsonb,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    planned_at timestamp with time zone,
    finished_at timestamp with time zone,
    error text
);

ALTER TABLE public.merge_run ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.merge_run_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.name_relation (
    project_id integer NOT NULL,
    id integer NOT NULL,
    usage_id integer NOT NULL,
    related_usage_id integer,
    type text,
    reference_id integer,
    page text,
    remarks text,
    modified timestamp with time zone DEFAULT now() NOT NULL,
    modified_by integer,
    version integer DEFAULT 0 NOT NULL
);

CREATE TABLE public.name_usage (
    id integer NOT NULL,
    project_id integer NOT NULL,
    alternative_id text[],
    parent_id integer,
    ordinal integer,
    status text NOT NULL,
    name_phrase text,
    reference_id integer[],
    scientific_name text NOT NULL,
    authorship text,
    rank text NOT NULL,
    uninomial text,
    genus text,
    infrageneric_epithet text,
    specific_epithet text,
    infraspecific_epithet text,
    cultivar_epithet text,
    notho text,
    combination_authorship text,
    combination_ex_authorship text,
    combination_authorship_year text,
    basionym_authorship text,
    basionym_ex_authorship text,
    basionym_authorship_year text,
    sanctioning_author text,
    nom_status text,
    published_in_reference_id integer,
    published_in_year integer,
    published_in_page text,
    published_in_page_link text,
    gender text,
    etymology text,
    name_type text,
    parse_state text,
    remarks text,
    modified timestamp with time zone DEFAULT now() NOT NULL,
    modified_by bigint,
    version integer DEFAULT 0 NOT NULL
);

CREATE TABLE public.project (
    id bigint NOT NULL,
    title text NOT NULL,
    alias text,
    description text,
    nom_code text,
    license text,
    geographic_scope text,
    taxonomic_scope text,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    gbif_occurrence_layer boolean DEFAULT true NOT NULL,
    identifier_scopes jsonb,
    is_public boolean DEFAULT false NOT NULL,
    csl_style text DEFAULT 'apa'::text NOT NULL,
    favorite_clb_datasets jsonb
);

ALTER TABLE public.project ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.project_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.project_member (
    project_id bigint NOT NULL,
    user_id bigint NOT NULL,
    role text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT project_member_role_check CHECK ((role = ANY (ARRAY['owner'::text, 'editor'::text, 'viewer'::text])))
);

CREATE TABLE public.property (
    project_id integer NOT NULL,
    id integer NOT NULL,
    usage_id integer NOT NULL,
    property text,
    value text,
    page text,
    reference_id integer,
    remarks text,
    modified timestamp with time zone DEFAULT now() NOT NULL,
    modified_by integer,
    version integer DEFAULT 0 NOT NULL
);

CREATE TABLE public.reference (
    id integer NOT NULL,
    project_id integer NOT NULL,
    alternative_id text[],
    citation text,
    type text,
    title text,
    container_title text,
    issued text,
    volume text,
    issue text,
    page text,
    publisher text,
    doi text,
    isbn text,
    issn text,
    link text,
    remarks text,
    modified timestamp with time zone DEFAULT now() NOT NULL,
    modified_by bigint,
    version integer DEFAULT 0 NOT NULL,
    accessed text,
    pdf text,
    author jsonb,
    editor jsonb,
    container_title_short text,
    citation_manual boolean DEFAULT false NOT NULL
);

CREATE TABLE public.release (
    id integer NOT NULL,
    project_id integer NOT NULL,
    version text NOT NULL,
    notes text,
    status text NOT NULL,
    name_usage_count integer,
    metrics jsonb,
    file_path text,
    file_name text,
    file_size bigint,
    error text,
    created_by integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.release ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.release_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.synonym_accepted (
    project_id integer NOT NULL,
    synonym_id integer NOT NULL,
    accepted_id integer NOT NULL,
    ordinal integer
);

CREATE TABLE public.task (
    id integer NOT NULL,
    project_id integer NOT NULL,
    user_id integer,
    title text NOT NULL,
    description text,
    status text DEFAULT 'OPEN'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    closed_at timestamp with time zone
);

ALTER TABLE public.task ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.task_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.taxon_info (
    project_id integer NOT NULL,
    usage_id integer NOT NULL,
    extinct boolean,
    environment text[],
    temporal_range_start text,
    temporal_range_end text
);

CREATE TABLE public.type_material (
    project_id integer NOT NULL,
    id integer NOT NULL,
    usage_id integer NOT NULL,
    citation text,
    status text,
    institution_code text,
    catalog_number text,
    occurrence_id text,
    locality text,
    country text,
    collector text,
    date text,
    sex text,
    reference_id integer,
    link text,
    remarks text,
    modified timestamp with time zone DEFAULT now() NOT NULL,
    modified_by integer,
    version integer DEFAULT 0 NOT NULL,
    latitude double precision,
    longitude double precision
);

CREATE TABLE public.vernacular (
    project_id integer NOT NULL,
    id integer NOT NULL,
    usage_id integer NOT NULL,
    name text,
    language text,
    country text,
    sex text,
    preferred boolean,
    reference_id integer,
    remarks text,
    modified timestamp with time zone DEFAULT now() NOT NULL,
    modified_by integer,
    version integer DEFAULT 0 NOT NULL
);

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_orcid_key UNIQUE (orcid);

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_username_key UNIQUE (username);

ALTER TABLE ONLY public.author
    ADD CONSTRAINT author_pkey PRIMARY KEY (project_id, id);

ALTER TABLE ONLY public.change
    ADD CONSTRAINT change_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.col_match_run
    ADD CONSTRAINT col_match_run_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.discussion_api_token
    ADD CONSTRAINT discussion_api_token_pkey PRIMARY KEY (project_id);

ALTER TABLE ONLY public.discussion_change
    ADD CONSTRAINT discussion_change_pkey PRIMARY KEY (project_id, discussion_id, change_id);

ALTER TABLE ONLY public.discussion_comment
    ADD CONSTRAINT discussion_comment_pkey PRIMARY KEY (project_id, id);

ALTER TABLE ONLY public.discussion_follow
    ADD CONSTRAINT discussion_follow_pkey PRIMARY KEY (project_id, discussion_id, user_id);

ALTER TABLE ONLY public.discussion
    ADD CONSTRAINT discussion_pkey PRIMARY KEY (project_id, id);

ALTER TABLE ONLY public.discussion_usage
    ADD CONSTRAINT discussion_usage_pkey PRIMARY KEY (project_id, discussion_id, usage_id);

ALTER TABLE ONLY public.distribution
    ADD CONSTRAINT distribution_pkey PRIMARY KEY (project_id, id);

ALTER TABLE ONLY public.estimate
    ADD CONSTRAINT estimate_pkey PRIMARY KEY (project_id, id);

ALTER TABLE ONLY public.export_run
    ADD CONSTRAINT export_run_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.id_seq
    ADD CONSTRAINT id_seq_pkey PRIMARY KEY (project_id, entity);

ALTER TABLE ONLY public.import_run
    ADD CONSTRAINT import_run_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.issue
    ADD CONSTRAINT issue_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.issue
    ADD CONSTRAINT issue_project_id_entity_type_entity_id_rule_key UNIQUE (project_id, entity_type, entity_id, rule);

ALTER TABLE ONLY public.join_request
    ADD CONSTRAINT join_request_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.join_request
    ADD CONSTRAINT join_request_project_id_orcid_key UNIQUE (project_id, orcid);

ALTER TABLE ONLY public.lock
    ADD CONSTRAINT lock_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.lock
    ADD CONSTRAINT lock_project_id_entity_type_entity_id_key UNIQUE (project_id, entity_type, entity_id);

ALTER TABLE ONLY public.media
    ADD CONSTRAINT media_pkey PRIMARY KEY (project_id, id);

ALTER TABLE ONLY public.merge_run
    ADD CONSTRAINT merge_run_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.name_relation
    ADD CONSTRAINT name_relation_pkey PRIMARY KEY (project_id, id);

ALTER TABLE ONLY public.name_usage
    ADD CONSTRAINT name_usage_pkey PRIMARY KEY (project_id, id);

ALTER TABLE ONLY public.project_member
    ADD CONSTRAINT project_member_pkey PRIMARY KEY (project_id, user_id);

ALTER TABLE ONLY public.project
    ADD CONSTRAINT project_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.property
    ADD CONSTRAINT property_pkey PRIMARY KEY (project_id, id);

ALTER TABLE ONLY public.reference
    ADD CONSTRAINT reference_pkey PRIMARY KEY (project_id, id);

ALTER TABLE ONLY public.release
    ADD CONSTRAINT release_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.synonym_accepted
    ADD CONSTRAINT synonym_accepted_pkey PRIMARY KEY (project_id, synonym_id, accepted_id);

ALTER TABLE ONLY public.task
    ADD CONSTRAINT task_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.taxon_info
    ADD CONSTRAINT taxon_info_pkey PRIMARY KEY (project_id, usage_id);

ALTER TABLE ONLY public.type_material
    ADD CONSTRAINT type_material_pkey PRIMARY KEY (project_id, id);

ALTER TABLE ONLY public.vernacular
    ADD CONSTRAINT vernacular_pkey PRIMARY KEY (project_id, id);

CREATE INDEX change_entity_idx ON public.change USING btree (project_id, entity_type, entity_id, at DESC);

CREATE INDEX change_project_at_idx ON public.change USING btree (project_id, at DESC, id DESC);

CREATE INDEX change_task_idx ON public.change USING btree (project_id, task_id);

CREATE UNIQUE INDEX col_match_run_active_idx ON public.col_match_run USING btree (project_id) WHERE (status = 'RUNNING'::text);

CREATE INDEX col_match_run_project_idx ON public.col_match_run USING btree (project_id, started_at DESC);

CREATE INDEX discussion_change_by_change_idx ON public.discussion_change USING btree (change_id);

CREATE INDEX discussion_comment_thread_idx ON public.discussion_comment USING btree (project_id, discussion_id, id);

CREATE INDEX discussion_follow_by_discussion_idx ON public.discussion_follow USING btree (project_id, discussion_id);

CREATE INDEX discussion_fts ON public.discussion USING gin (to_tsvector('simple'::regconfig, ((COALESCE(title, ''::text) || ' '::text) || COALESCE(body, ''::text))));

CREATE INDEX discussion_project_author_idx ON public.discussion USING btree (project_id, author_id);

CREATE INDEX discussion_project_status_idx ON public.discussion USING btree (project_id, status);

CREATE INDEX discussion_usage_by_usage_idx ON public.discussion_usage USING btree (project_id, usage_id);

CREATE INDEX distribution_usage_idx ON public.distribution USING btree (project_id, usage_id);

CREATE INDEX estimate_usage_idx ON public.estimate USING btree (project_id, usage_id);

CREATE UNIQUE INDEX export_run_active_idx ON public.export_run USING btree (project_id) WHERE (status = 'RUNNING'::text);

CREATE INDEX export_run_project_idx ON public.export_run USING btree (project_id, started_at DESC);

CREATE INDEX import_run_user_idx ON public.import_run USING btree (user_id, started_at DESC);

CREATE INDEX issue_entity_idx ON public.issue USING btree (project_id, entity_type, entity_id);

CREATE INDEX issue_project_status_idx ON public.issue USING btree (project_id, status, severity);

CREATE INDEX join_request_project_idx ON public.join_request USING btree (project_id);

CREATE INDEX lock_project_idx ON public.lock USING btree (project_id);

CREATE INDEX media_usage_idx ON public.media USING btree (project_id, usage_id);

CREATE UNIQUE INDEX merge_run_active_idx ON public.merge_run USING btree (target_project_id) WHERE (status = ANY (ARRAY['RUNNING'::text, 'APPLYING'::text]));

CREATE INDEX merge_run_target_idx ON public.merge_run USING btree (target_project_id, started_at DESC);

CREATE INDEX name_relation_usage_idx ON public.name_relation USING btree (project_id, usage_id);

CREATE INDEX name_usage_parent_idx ON public.name_usage USING btree (project_id, parent_id);

CREATE INDEX name_usage_sciname_trgm ON public.name_usage USING gin (scientific_name public.gin_trgm_ops);

CREATE INDEX project_member_user_idx ON public.project_member USING btree (user_id);

CREATE INDEX property_usage_idx ON public.property USING btree (project_id, usage_id);

CREATE INDEX reference_citation_fts ON public.reference USING gin (to_tsvector('simple'::regconfig, COALESCE(citation, ''::text)));

CREATE INDEX reference_citation_trgm ON public.reference USING gin (citation public.gin_trgm_ops);

CREATE INDEX release_project_idx ON public.release USING btree (project_id, created_at DESC, id DESC);

CREATE INDEX synonym_accepted_accepted_idx ON public.synonym_accepted USING btree (project_id, accepted_id);

CREATE INDEX task_project_idx ON public.task USING btree (project_id, status);

CREATE INDEX type_material_usage_idx ON public.type_material USING btree (project_id, usage_id);

CREATE INDEX vernacular_usage_idx ON public.vernacular USING btree (project_id, usage_id);

ALTER TABLE ONLY public.author
    ADD CONSTRAINT author_modified_by_fkey FOREIGN KEY (modified_by) REFERENCES public.app_user(id);

ALTER TABLE ONLY public.author
    ADD CONSTRAINT author_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.change
    ADD CONSTRAINT change_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.change
    ADD CONSTRAINT change_task_id_fkey FOREIGN KEY (task_id) REFERENCES public.task(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.change
    ADD CONSTRAINT change_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.col_match_run
    ADD CONSTRAINT col_match_run_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.discussion_api_token
    ADD CONSTRAINT discussion_api_token_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.discussion
    ADD CONSTRAINT discussion_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.app_user(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.discussion_change
    ADD CONSTRAINT discussion_change_change_id_fkey FOREIGN KEY (change_id) REFERENCES public.change(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.discussion_change
    ADD CONSTRAINT discussion_change_project_id_discussion_id_fkey FOREIGN KEY (project_id, discussion_id) REFERENCES public.discussion(project_id, id) ON DELETE CASCADE;

ALTER TABLE ONLY public.discussion_comment
    ADD CONSTRAINT discussion_comment_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.app_user(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.discussion_comment
    ADD CONSTRAINT discussion_comment_project_id_discussion_id_fkey FOREIGN KEY (project_id, discussion_id) REFERENCES public.discussion(project_id, id) ON DELETE CASCADE;

ALTER TABLE ONLY public.discussion_comment
    ADD CONSTRAINT discussion_comment_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.discussion_follow
    ADD CONSTRAINT discussion_follow_project_id_discussion_id_fkey FOREIGN KEY (project_id, discussion_id) REFERENCES public.discussion(project_id, id) ON DELETE CASCADE;

ALTER TABLE ONLY public.discussion_follow
    ADD CONSTRAINT discussion_follow_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.discussion
    ADD CONSTRAINT discussion_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.discussion_usage
    ADD CONSTRAINT discussion_usage_project_id_discussion_id_fkey FOREIGN KEY (project_id, discussion_id) REFERENCES public.discussion(project_id, id) ON DELETE CASCADE;

ALTER TABLE ONLY public.discussion_usage
    ADD CONSTRAINT discussion_usage_project_id_usage_id_fkey FOREIGN KEY (project_id, usage_id) REFERENCES public.name_usage(project_id, id) ON DELETE CASCADE;

ALTER TABLE ONLY public.distribution
    ADD CONSTRAINT distribution_project_id_usage_id_fkey FOREIGN KEY (project_id, usage_id) REFERENCES public.name_usage(project_id, id) ON DELETE CASCADE;

ALTER TABLE ONLY public.estimate
    ADD CONSTRAINT estimate_project_id_usage_id_fkey FOREIGN KEY (project_id, usage_id) REFERENCES public.name_usage(project_id, id) ON DELETE CASCADE;

ALTER TABLE ONLY public.export_run
    ADD CONSTRAINT export_run_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.import_run
    ADD CONSTRAINT import_run_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.import_run
    ADD CONSTRAINT import_run_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_user(id);

ALTER TABLE ONLY public.issue
    ADD CONSTRAINT issue_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.issue
    ADD CONSTRAINT issue_reviewer_id_fkey FOREIGN KEY (reviewer_id) REFERENCES public.app_user(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.join_request
    ADD CONSTRAINT join_request_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.lock
    ADD CONSTRAINT lock_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.lock
    ADD CONSTRAINT lock_task_id_fkey FOREIGN KEY (task_id) REFERENCES public.task(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.lock
    ADD CONSTRAINT lock_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.media
    ADD CONSTRAINT media_project_id_usage_id_fkey FOREIGN KEY (project_id, usage_id) REFERENCES public.name_usage(project_id, id) ON DELETE CASCADE;

ALTER TABLE ONLY public.merge_run
    ADD CONSTRAINT merge_run_source_project_id_fkey FOREIGN KEY (source_project_id) REFERENCES public.project(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.merge_run
    ADD CONSTRAINT merge_run_target_project_id_fkey FOREIGN KEY (target_project_id) REFERENCES public.project(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.merge_run
    ADD CONSTRAINT merge_run_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_user(id);

ALTER TABLE ONLY public.name_relation
    ADD CONSTRAINT name_relation_project_id_usage_id_fkey FOREIGN KEY (project_id, usage_id) REFERENCES public.name_usage(project_id, id) ON DELETE CASCADE;

ALTER TABLE ONLY public.name_usage
    ADD CONSTRAINT name_usage_modified_by_fkey FOREIGN KEY (modified_by) REFERENCES public.app_user(id);

ALTER TABLE ONLY public.name_usage
    ADD CONSTRAINT name_usage_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.name_usage
    ADD CONSTRAINT name_usage_project_id_parent_id_fkey FOREIGN KEY (project_id, parent_id) REFERENCES public.name_usage(project_id, id) ON DELETE SET NULL (parent_id);

ALTER TABLE ONLY public.name_usage
    ADD CONSTRAINT name_usage_project_id_published_in_reference_id_fkey FOREIGN KEY (project_id, published_in_reference_id) REFERENCES public.reference(project_id, id) ON DELETE SET NULL (published_in_reference_id);

ALTER TABLE ONLY public.project_member
    ADD CONSTRAINT project_member_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.project_member
    ADD CONSTRAINT project_member_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.property
    ADD CONSTRAINT property_project_id_usage_id_fkey FOREIGN KEY (project_id, usage_id) REFERENCES public.name_usage(project_id, id) ON DELETE CASCADE;

ALTER TABLE ONLY public.reference
    ADD CONSTRAINT reference_modified_by_fkey FOREIGN KEY (modified_by) REFERENCES public.app_user(id);

ALTER TABLE ONLY public.reference
    ADD CONSTRAINT reference_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.release
    ADD CONSTRAINT release_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.app_user(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.release
    ADD CONSTRAINT release_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.synonym_accepted
    ADD CONSTRAINT synonym_accepted_project_id_accepted_id_fkey FOREIGN KEY (project_id, accepted_id) REFERENCES public.name_usage(project_id, id) ON DELETE CASCADE;

ALTER TABLE ONLY public.synonym_accepted
    ADD CONSTRAINT synonym_accepted_project_id_synonym_id_fkey FOREIGN KEY (project_id, synonym_id) REFERENCES public.name_usage(project_id, id) ON DELETE CASCADE;

ALTER TABLE ONLY public.task
    ADD CONSTRAINT task_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.project(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.task
    ADD CONSTRAINT task_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.taxon_info
    ADD CONSTRAINT taxon_info_project_id_usage_id_fkey FOREIGN KEY (project_id, usage_id) REFERENCES public.name_usage(project_id, id) ON DELETE CASCADE;

ALTER TABLE ONLY public.type_material
    ADD CONSTRAINT type_material_project_id_usage_id_fkey FOREIGN KEY (project_id, usage_id) REFERENCES public.name_usage(project_id, id) ON DELETE CASCADE;

ALTER TABLE ONLY public.vernacular
    ADD CONSTRAINT vernacular_project_id_usage_id_fkey FOREIGN KEY (project_id, usage_id) REFERENCES public.name_usage(project_id, id) ON DELETE CASCADE;

