import type { NameUsage } from '../api/types';

// A complete NameUsage for component tests: sensible accepted-species defaults, overridden per test.
export function makeUsage(partial: Partial<NameUsage>): NameUsage {
  return {
    id: 200,
    parentId: null,
    status: 'ACCEPTED',
    scientificName: 'Panthera leo',
    authorship: null,
    rank: 'species',
    acceptedParentIds: null,
    synonymIds: null,
    version: 0,
    namePhrase: null,
    referenceId: null,
    extinct: null,
    environment: null,
    temporalRangeStart: null,
    temporalRangeEnd: null,
    uninomial: null,
    genus: null,
    infragenericEpithet: null,
    specificEpithet: 'leo',
    infraspecificEpithet: null,
    cultivarEpithet: null,
    notho: null,
    combinationAuthorship: null,
    combinationExAuthorship: null,
    combinationAuthorshipYear: null,
    basionymAuthorship: null,
    basionymExAuthorship: null,
    basionymAuthorshipYear: null,
    sanctioningAuthor: null,
    nomStatus: null,
    publishedInReferenceId: null,
    publishedInYear: null,
    publishedInPage: null,
    publishedInPageLink: null,
    gender: null,
    genderAgreement: null,
    genusGender: null,
    genusId: null,
    genusName: null,
    etymology: null,
    nameType: null,
    parseState: null,
    remarks: null,
    formattedName: null,
    ...partial,
  } as NameUsage;
}
