spring:
  application:
    name: coldp-editor
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/coldp_editor}
    username: ${DB_USER:coldp_editor}
    password: ${DB_PASSWORD:coldp_editor}
  flyway:
    enabled: true
  security:
    oauth2:
      client:
        registration:
          orcid:
            client-id: ${ORCID_CLIENT_ID:unconfigured}
            client-secret: ${ORCID_CLIENT_SECRET:unconfigured}
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/orcid"
            client-name: ORCID
        provider:
          orcid:
            authorization-uri: https://orcid.org/oauth/authorize
            token-uri: https://orcid.org/oauth/token
            user-info-uri: https://orcid.org/oauth/userinfo
            jwk-set-uri: https://orcid.org/oauth/jwks
            user-name-attribute: sub
mybatis:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8080
coldp:
  clb:
    base-url: https://api.checklistbank.org
  col:
    match-dataset: 3LXR
    gbif-checklist-key: 7ddf754f-d193-4cc9-b351-99906754a03b
  export:
    dir: ${java.io.tmpdir}/coldp-exports
    ttl: P7D
